// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oip.Hitl.Data.Contexts;

#nullable disable

namespace Oip.Hitl.Data.Migrations.Postgres
{
    [DbContext(typeof(LlmContextPostgres))]
    [Migration("20261004140517_RegisteredTools_Postgres")]
    partial class RegisteredTools_Postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oip.Hitl.Data.Entities.AgentEntity", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AgentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Model id of the agent in the OpenAI-compatible API, e.g. support-agent.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Description for administrators.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("Whether the agent is offered to chat UIs.");

                    b.Property<int?>("LlmProviderId")
                        .HasColumnType("integer")
                        .HasComment("Provider that answers; null for the default provider.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Human-readable name shown in the UI.");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text")
                        .HasComment("System prompt of the agent; the list of its skills is added to it.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last update timestamp (UTC).");

                    b.HasKey("AgentId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LlmProviderId");

                    b.ToTable("Agent", "llm", t =>
                        {
                            t.HasComment("Agent exposed to chat UIs as a model: a system prompt, the LLM provider that answers and the skills it may load.");
                        });
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.AgentSkillEntity", b =>
                {
                    b.Property<int>("AgentId")
                        .HasColumnType("integer")
                        .HasComment("Agent.");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasComment("Skill.");

                    b.HasKey("AgentId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("AgentSkill", "llm", t =>
                        {
                            t.HasComment("Skill an agent may load.");
                        });
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.LlmProviderEntity", b =>
                {
                    b.Property<int>("LlmProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LlmProviderId"));

                    b.Property<string>("ApiKeyProtected")
                        .HasColumnType("text")
                        .HasComment("API key protected with ASP.NET Core Data Protection. Null when no key is configured.");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("API base URL, e.g. https://api.openai.com/v1.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasComment("Whether this provider is used when no provider is specified explicitly. At most one provider is default.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("Whether the provider can be used.");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Default model identifier, e.g. gpt-4o-mini.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Human-readable name shown in the UI.");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Provider API kind.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last update timestamp (UTC).");

                    b.HasKey("LlmProviderId");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProvider", "llm", t =>
                        {
                            t.HasComment("Stored LLM provider configuration.");
                        });
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.RegisteredToolEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name of the tool, the primary key.");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Temporal name of the activity.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("What the tool does.");

                    b.Property<bool>("HasArguments")
                        .HasColumnType("boolean")
                        .HasComment("Whether the activity takes the arguments object as its parameter.");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasComment("Attempts before the failure is returned to the model.");

                    b.Property<string>("ParametersSchema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("JSON schema of the arguments object.");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When the worker registered the tool (UTC).");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasComment("Whether the user allows each call before it is made.");

                    b.Property<string>("TaskQueue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Task queue the worker of the tool polls.");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasComment("Timeout of an attempt in seconds.");

                    b.HasKey("Name");

                    b.HasIndex("TaskQueue");

                    b.ToTable("RegisteredTool", "llm", t =>
                        {
                            t.HasComment("Tool registered by a skill worker: an activity of the worker the model may call, on the task queue of the worker.\n            The worker replaces its tools when it starts.");
                        });
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.SkillEntity", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name the model loads the skill by, e.g. datetime.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("When to use the skill; always shown to the model.");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("How to do the task; given to the model when it loads the skill.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("Whether agents may load the skill.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last update timestamp (UTC).");

                    b.HasKey("SkillId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Skill", "llm", t =>
                        {
                            t.HasComment("Skill of agents: instructions and tools for a kind of task. The model sees only  until\n            it loads the skill; then it gets  and the tools.");
                        });
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.SkillToolEntity", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasComment("Skill.");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name of the tool, e.g. get_current_time.");

                    b.HasKey("SkillId", "ToolName");

                    b.ToTable("SkillTool", "llm", t =>
                        {
                            t.HasComment("Tool a skill gives the model, by its name in the tool catalog.");
                        });
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.AgentEntity", b =>
                {
                    b.HasOne("Oip.Hitl.Data.Entities.LlmProviderEntity", "LlmProvider")
                        .WithMany()
                        .HasForeignKey("LlmProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LlmProvider");
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.AgentSkillEntity", b =>
                {
                    b.HasOne("Oip.Hitl.Data.Entities.AgentEntity", "Agent")
                        .WithMany("Skills")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oip.Hitl.Data.Entities.SkillEntity", "Skill")
                        .WithMany("Agents")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.SkillToolEntity", b =>
                {
                    b.HasOne("Oip.Hitl.Data.Entities.SkillEntity", "Skill")
                        .WithMany("Tools")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.AgentEntity", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Oip.Hitl.Data.Entities.SkillEntity", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
