// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Oip.Hitl.Data.Contexts;

namespace Oip.Hitl.Data.Migrations.Postgres
{
    [DbContext(typeof(LlmContextPostgres))]
    [Migration("20260927114408_InitialLlm_Postgres")]
    partial class InitialLlm_Postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oip.Hitl.Data.Entities.LlmProviderEntity", b =>
                {
                    b.Property<int>("LlmProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LlmProviderId"));

                    b.Property<string>("ApiKeyProtected")
                        .HasColumnType("text")
                        .HasComment("API key protected with ASP.NET Core Data Protection. Null when no key is configured.");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("API base URL, e.g. https://api.openai.com/v1.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasComment("Whether this provider is used when no provider is specified explicitly. At most one provider is default.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("Whether the provider can be used.");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Default model identifier, e.g. gpt-4o-mini.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Human-readable name shown in the UI.");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Provider API kind.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last update timestamp (UTC).");

                    b.HasKey("LlmProviderId");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProvider", "llm", t =>
                        {
                            t.HasComment("Stored LLM provider configuration.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
