<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="Octonica.ClickHouseClient" />

        <PackageReference Include="Microsoft.CodeAnalysis.Common" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Oip.Base\Oip.Base.csproj" />
        <ProjectReference Include="..\Oip.Rtds.Base\Oip.Rtds.Base.csproj" />
    </ItemGroup>

</Project>
