<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>oip</ToolCommandName>
        <PackageId>Oip.Cli</PackageId>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Command-line tool for generating OIP modules.</Title>
    </PropertyGroup>

    <ItemGroup>
        <None Include=".\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
