<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Discussion contracts for OIP template</Title>
    </PropertyGroup>
    <ItemGroup>
        <None Include=".\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Minio" />
        <PackageReference Include="NLog"/>
        <PackageReference Include="NLog.Web.AspNetCore"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Oip.Base\Oip.Base.csproj"/>
        <ProjectReference Include="..\Oip.Users.Base\Oip.Users.Base.csproj"/>
    </ItemGroup>
</Project>
