<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Real-time data service contracts for OIP template</Title>
    </PropertyGroup>

    <ItemGroup>
        <None Include=".\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\rtds_service.proto" GrpcServices="Client">
            <Generator>MSBuild:Compile</Generator>
        </Protobuf>
        <Protobuf Include="Protos\rtds_service.proto" GrpcServices="GrpcServices">
            <Generator>MSBuild:Compile</Generator>
        </Protobuf>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Grpc.Net.ClientFactory" />
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    </ItemGroup>
    
</Project>
