// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oip.Base.Data.Contexts;

#nullable disable

namespace Oip.Base.Data.Migrations.Postgres
{
    [DbContext(typeof(OipModuleContextPostgres))]
    [Migration("20251102170452_AlignmentMigration_Postgres")]
    partial class AlignmentMigration_Postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oip.Data.Entities.ModuleEntity", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Name");

                    b.Property<string>("RouterLink")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Route link to component");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasComment("Settings for module");

                    b.ToTable("Module", "oip", t =>
                        {
                            t.HasComment("Module entity");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.ModuleInstanceEntity", b =>
                {
                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Label");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasComment("Label");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasComment("Module id");

                    b.Property<int>("ModuleInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleInstanceId"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasComment("Parent id");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Settings");

                    b.Property<string>("Target")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("Target");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComment("Url");

                    b.ToTable("ModuleInstance", "oip", t =>
                        {
                            t.HasComment("Module instance");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.ModuleInstanceSecurityEntity", b =>
                {
                    b.Property<int>("ModuleInstanceId")
                        .HasColumnType("integer")
                        .HasComment("ModuleId");

                    b.Property<int>("ModuleInstanceSecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleInstanceSecurityId"));

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Right (max 255 chars)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Role (max 255 chars)");

                    b.ToTable("ModuleInstanceSecurity", "oip", t =>
                        {
                            t.HasComment("Module instance security entity");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.ModuleSecurityEntity", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasComment("ModuleId");

                    b.Property<int>("ModuleSecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleSecurityId"));

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Right");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Role");

                    b.ToTable("ModuleSecurity", "oip", t =>
                        {
                            t.HasComment("Module security entity");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("E-mail");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasComment("User photo");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("User id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.ToTable("User", "oip", t =>
                        {
                            t.HasComment("User entity");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
