// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oip.Hil.Data.Contexts;

#nullable disable

namespace Oip.Hil.Data.Migrations.SqlServer
{
    [DbContext(typeof(LlmContextSqlServer))]
    [Migration("20260927114429_InitialLlm_SqlServer")]
    partial class InitialLlm_SqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oip.Hil.Data.Entities.LlmProviderEntity", b =>
                {
                    b.Property<int>("LlmProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LlmProviderId"));

                    b.Property<string>("ApiKeyProtected")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("API key protected with ASP.NET Core Data Protection. Null when no key is configured.");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("API base URL, e.g. https://api.openai.com/v1.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasComment("Whether this provider is used when no provider is specified explicitly. At most one provider is default.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasComment("Whether the provider can be used.");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Default model identifier, e.g. gpt-4o-mini.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Human-readable name shown in the UI.");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Provider API kind.");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Last update timestamp (UTC).");

                    b.HasKey("LlmProviderId");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProvider", "llm", t =>
                        {
                            t.HasComment("Stored LLM provider configuration.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
