// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oip.Rtds.Data.Contexts;

#nullable disable

namespace Oip.Rtds.Data.Postgres.Migrations
{
    [DbContext(typeof(RtdsMetaContext))]
    [Migration("20250612082029_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oip.Rtds.Data.Entities.TagEntity", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TagId"));

                    b.Property<bool?>("Archiving")
                        .HasColumnType("boolean");

                    b.Property<double?>("CompDev")
                        .HasColumnType("double precision");

                    b.Property<int?>("CompMax")
                        .HasColumnType("integer");

                    b.Property<int?>("CompMin")
                        .HasColumnType("integer");

                    b.Property<bool?>("Compressing")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Descriptor")
                        .HasColumnType("text");

                    b.Property<string>("DigitalSet")
                        .HasColumnType("text");

                    b.Property<string>("EngUnits")
                        .HasColumnType("text");

                    b.Property<string>("ExDesc")
                        .HasColumnType("text");

                    b.Property<double?>("ExcDev")
                        .HasColumnType("double precision");

                    b.Property<int?>("ExcMax")
                        .HasColumnType("integer");

                    b.Property<int?>("ExcMin")
                        .HasColumnType("integer");

                    b.Property<bool?>("Future")
                        .HasColumnType("boolean");

                    b.Property<string>("InstrumentTag")
                        .HasColumnType("text");

                    b.Property<int?>("Location1")
                        .HasColumnType("integer");

                    b.Property<int?>("Location2")
                        .HasColumnType("integer");

                    b.Property<int?>("Location3")
                        .HasColumnType("integer");

                    b.Property<int?>("Location4")
                        .HasColumnType("integer");

                    b.Property<int?>("Location5")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Partition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Scan")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int?>("Span")
                        .HasColumnType("integer");

                    b.Property<bool?>("Step")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserInt1")
                        .HasColumnType("integer");

                    b.Property<int?>("UserInt2")
                        .HasColumnType("integer");

                    b.Property<int?>("UserInt3")
                        .HasColumnType("integer");

                    b.Property<int?>("UserInt4")
                        .HasColumnType("integer");

                    b.Property<int?>("UserInt5")
                        .HasColumnType("integer");

                    b.Property<double?>("UserReal1")
                        .HasColumnType("double precision");

                    b.Property<double?>("UserReal2")
                        .HasColumnType("double precision");

                    b.Property<double?>("UserReal3")
                        .HasColumnType("double precision");

                    b.Property<double?>("UserReal4")
                        .HasColumnType("double precision");

                    b.Property<double?>("UserReal5")
                        .HasColumnType("double precision");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.Property<int?>("Zero")
                        .HasColumnType("integer");

                    b.HasKey("TagId");

                    b.ToTable("Tag", "rtds");
                });
#pragma warning restore 612, 618
        }
    }
}
