//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oip.Security.Bl.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResourceServiceResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResourceServiceResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Oip.Security.Bl.Resources.ApiResourceServiceResource", typeof(ApiResourceServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApiResourceDoesNotExist {
            get {
                return ResourceManager.GetString("ApiResourceDoesNotExist", resourceCulture);
            }
        }
        
        internal static string ApiResourceExistsKey {
            get {
                return ResourceManager.GetString("ApiResourceExistsKey", resourceCulture);
            }
        }
        
        internal static string ApiResourceExistsValue {
            get {
                return ResourceManager.GetString("ApiResourceExistsValue", resourceCulture);
            }
        }
        
        internal static string ApiResourcePropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ApiResourcePropertyDoesNotExist", resourceCulture);
            }
        }
        
        internal static string ApiResourcePropertyExistsKey {
            get {
                return ResourceManager.GetString("ApiResourcePropertyExistsKey", resourceCulture);
            }
        }
        
        internal static string ApiResourcePropertyExistsValue {
            get {
                return ResourceManager.GetString("ApiResourcePropertyExistsValue", resourceCulture);
            }
        }
        
        internal static string ApiSecretDoesNotExist {
            get {
                return ResourceManager.GetString("ApiSecretDoesNotExist", resourceCulture);
            }
        }
    }
}
