//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oip.Security.Bl.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdentityResourceServiceResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResourceServiceResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Oip.Security.Bl.Resources.IdentityResourceServiceResource", typeof(IdentityResourceServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IdentityResourceDoesNotExist {
            get {
                return ResourceManager.GetString("IdentityResourceDoesNotExist", resourceCulture);
            }
        }
        
        internal static string IdentityResourceExistsKey {
            get {
                return ResourceManager.GetString("IdentityResourceExistsKey", resourceCulture);
            }
        }
        
        internal static string IdentityResourceExistsValue {
            get {
                return ResourceManager.GetString("IdentityResourceExistsValue", resourceCulture);
            }
        }
        
        internal static string IdentityResourcePropertyDoesNotExist {
            get {
                return ResourceManager.GetString("IdentityResourcePropertyDoesNotExist", resourceCulture);
            }
        }
        
        internal static string IdentityResourcePropertyExistsKey {
            get {
                return ResourceManager.GetString("IdentityResourcePropertyExistsKey", resourceCulture);
            }
        }
        
        internal static string IdentityResourcePropertyExistsValue {
            get {
                return ResourceManager.GetString("IdentityResourcePropertyExistsValue", resourceCulture);
            }
        }
    }
}
