// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oip.Applications.Data;

#nullable disable

namespace Oip.Applications.Data.Migrations.SqlServer
{
    [DbContext(typeof(ApplicationRegistryDbContextSqlServer))]
    partial class ApplicationRegistryDbContextSqlServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oip.Applications.Data.ApplicationRegistryItemEntity", b =>
                {
                    b.Property<long>("ApplicationRegistryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal database identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApplicationRegistryItemId"));

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Backend API URL.");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Frontend application URL.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Stable application code.");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Human-readable application name.");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indicates whether application should be returned to frontend.");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("PrimeIcons CSS class.");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasComment("Display order.");

                    b.HasKey("ApplicationRegistryItemId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ApplicationRegistryItem", "applications", t =>
                        {
                            t.HasComment("Persisted frontend application registry item.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
