// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oip.Settings.Contexts;

#nullable disable

namespace Oip.Settings.Migrations.Sqlite
{
    [DbContext(typeof(SqliteMigrationContext))]
    [Migration("20231202115541_Initialize_SQLite")]
    partial class Initialize_SQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.22");

            modelBuilder.Entity("Oip.Settings.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable(AppSettingsTable, (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
