// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Oip.Data.Contexts;

namespace Oip.Data.Migrations.SqlServer
{
    [DbContext(typeof(OipModuleContextSqlServer))]
    [Migration("20250518130749_AddComment")]
    partial class AddComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oip.Data.Entities.ModuleEntity", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Name");

                    b.Property<string>("RouterLink")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Route link to component");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Settings for module");

                    b.ToTable("Module", "oip", t =>
                        {
                            t.HasComment("Module entity");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.ModuleInstanceEntity", b =>
                {
                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Label");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Label");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasComment("Module id");

                    b.Property<int>("ModuleInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleInstanceId"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasComment("Parent id");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Settings");

                    b.Property<string>("Target")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Target");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Url");

                    b.ToTable("ModuleInstance", "oip", t =>
                        {
                            t.HasComment("Module instance");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.ModuleInstanceSecurityEntity", b =>
                {
                    b.Property<int>("ModuleInstanceId")
                        .HasColumnType("int")
                        .HasComment("ModuleId");

                    b.Property<int>("ModuleInstanceSecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleInstanceSecurityId"));

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Right (max 255 chars)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Role (max 255 chars)");

                    b.ToTable("ModuleInstanceSecurity", "oip", t =>
                        {
                            t.HasComment("Module instance security entity");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.ModuleSecurityEntity", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasComment("ModuleId");

                    b.Property<int>("ModuleSecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleSecurityId"));

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Right");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Role");

                    b.ToTable("ModuleSecurity", "oip", t =>
                        {
                            t.HasComment("Module security entity");
                        });
                });

            modelBuilder.Entity("Oip.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("E-mail");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)")
                        .HasComment("");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("User id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.ToTable("User", "oip", t =>
                        {
                            t.HasComment("User entity");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
