// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oip.Notifications.Data.Contexts;

#nullable disable

namespace Oip.Notifications.Migrations.SqlServer
{
    [DbContext(typeof(NotificationsDbContextSqlServer))]
    [Migration("20260105113938_AddNotificationChannelCodeColumn_SqlServer")]
    partial class AddNotificationChannelCodeColumn_SqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKey", "notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendlyName = "key-b57db670-000b-4dd7-8603-e82a29941b6d",
                            Xml = "<key id=\"b57db670-000b-4dd7-8603-e82a29941b6d\" version=\"1\"><creationDate>2025-12-31T12:29:13.551409Z</creationDate><activationDate>2025-12-31T12:29:13.395011Z</activationDate><expirationDate>2125-12-07T12:29:13.395011Z</expirationDate><descriptor deserializerType=\"Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60\"><descriptor><encryption algorithm=\"AES_256_CBC\" /><validation algorithm=\"HMACSHA256\" /><masterKey p4:requiresEncryption=\"true\" xmlns:p4=\"http://schemas.asp.net/2015/03/dataProtection\"><!-- Warning: the key below is in an unencrypted form. --><value>y6SO3S3B9NggxGQguIPpg3kCnMYSJt9bed1u8VFDIOqmL4eyzvBZLuLHJY74ASdSAlNW5ayiRDWnWhEzc95IcA==</value></masterKey></descriptor></descriptor></key>"
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationChannelEntity", b =>
                {
                    b.Property<int>("NotificationChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the notification channel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationChannelId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Name of the notification channel");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Whether the channel is active");

                    b.Property<int?>("MaxRetryCount")
                        .HasColumnType("int")
                        .HasComment("Maximum number of delivery retry attempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the notification channel");

                    b.Property<bool>("RequiresVerification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Whether the channel requires user verification");

                    b.HasKey("NotificationChannelId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NotificationChannel", "notifications", t =>
                        {
                            t.HasComment("Notification delivery channels");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationDeliveryEntity", b =>
                {
                    b.Property<long>("NotificationDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier for the notification delivery");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationDeliveryId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp of the delivery record");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Timestamp when the notification was delivered");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Error message if delivery failed");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("External identifier from the delivery service");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("int")
                        .HasComment("Notification channel identifier");

                    b.Property<long>("NotificationUserId")
                        .HasColumnType("bigint")
                        .HasComment("Notification user identifier");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Number of delivery retry attempts");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Timestamp when the notification was sent");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Delivery status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("User identifier");

                    b.HasKey("NotificationDeliveryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalId");

                    b.HasIndex("NotificationChannelId");

                    b.HasIndex("NotificationUserId");

                    b.HasIndex("SentAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "RetryCount");

                    b.ToTable("NotificationDelivery", "notifications", t =>
                        {
                            t.HasComment("Notification delivery history by channels");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier for the notification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp of the notification");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON data associated with the notification");

                    b.Property<int>("Importance")
                        .HasColumnType("int")
                        .HasComment("Importance level of the notification");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int")
                        .HasComment("Notification type identifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Importance");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notification", "notifications", t =>
                        {
                            t.HasComment("Notification/event");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTemplateChannelEntity", b =>
                {
                    b.Property<int>("NotificationTemplateChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the template-channel association");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTemplateChannelId"));

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("int")
                        .HasComment("Notification channel identifier");

                    b.Property<int>("NotificationTemplateId")
                        .HasColumnType("int")
                        .HasComment("Notification template identifier");

                    b.HasKey("NotificationTemplateChannelId");

                    b.HasIndex("NotificationChannelId");

                    b.HasIndex("NotificationTemplateId", "NotificationChannelId")
                        .IsUnique();

                    b.ToTable("NotificationTemplateChannel", "notifications", t =>
                        {
                            t.HasComment("Association between a notification template and a notification channel");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTemplateEntity", b =>
                {
                    b.Property<int>("NotificationTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the notification template");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTemplateId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Whether the notification template is currently active");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Message template for the notification");

                    b.Property<int?>("NotificationChannelEntityNotificationChannelId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the notification type");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Subject template for the notification");

                    b.HasKey("NotificationTemplateId");

                    b.HasIndex("NotificationChannelEntityNotificationChannelId");

                    b.HasIndex("NotificationTypeId", "IsActive");

                    b.ToTable("NotificationTemplate", "notifications", t =>
                        {
                            t.HasComment("Notification template for different channels");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTemplateUserEntity", b =>
                {
                    b.Property<int>("NotificationTemplateUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the template-user mapping");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTemplateUserId"));

                    b.Property<int>("NotificationTemplateId")
                        .HasColumnType("int")
                        .HasComment("Notification template identifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("User identifier");

                    b.HasKey("NotificationTemplateUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("NotificationTemplateId", "UserId")
                        .IsUnique();

                    b.ToTable("NotificationTemplateUser", "notifications", t =>
                        {
                            t.HasComment("Mapping between a notification template and a user");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTypeEntity", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the notification type");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Detailed explanation of the notification type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Name of the notification type");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Scope of notification type (global, appName, feature)");

                    b.HasKey("NotificationTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Scope");

                    b.ToTable("NotificationType", "notifications", t =>
                        {
                            t.HasComment("Type of notification within the system");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationUserEntity", b =>
                {
                    b.Property<long>("NotificationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier for the notification user");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationUserId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Message of the notification for this user");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint")
                        .HasComment("Notification identifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Subject of the notification for this user");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("User identifier");

                    b.HasKey("NotificationUserId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.HasIndex("NotificationId", "UserId")
                        .IsUnique();

                    b.ToTable("NotificationUser", "notifications", t =>
                        {
                            t.HasComment("Users who should be notified about an event");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.UserNotificationPreferenceEntity", b =>
                {
                    b.Property<int>("UserNotificationPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the user notification preference");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserNotificationPreferenceId"));

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Whether notifications are enabled for this preference");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("int")
                        .HasComment("Notification channel identifier");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int")
                        .HasComment("Notification type identifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("User identifier");

                    b.HasKey("UserNotificationPreferenceId");

                    b.HasIndex("NotificationChannelId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsEnabled");

                    b.HasIndex("UserId", "NotificationTypeId", "NotificationChannelId")
                        .IsUnique();

                    b.ToTable("UserNotificationPreference", "notifications", t =>
                        {
                            t.HasComment("User notification preferences");
                        });
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationDeliveryEntity", b =>
                {
                    b.HasOne("Oip.Notifications.Data.Entities.NotificationChannelEntity", "NotificationChannel")
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Oip.Notifications.Data.Entities.NotificationUserEntity", "NotificationUser")
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationChannel");

                    b.Navigation("NotificationUser");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("Oip.Notifications.Data.Entities.NotificationTypeEntity", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTemplateChannelEntity", b =>
                {
                    b.HasOne("Oip.Notifications.Data.Entities.NotificationChannelEntity", "NotificationChannel")
                        .WithMany()
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oip.Notifications.Data.Entities.NotificationTemplateEntity", "NotificationTemplate")
                        .WithMany("NotificationTemplateChannels")
                        .HasForeignKey("NotificationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationChannel");

                    b.Navigation("NotificationTemplate");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTemplateEntity", b =>
                {
                    b.HasOne("Oip.Notifications.Data.Entities.NotificationChannelEntity", null)
                        .WithMany("Templates")
                        .HasForeignKey("NotificationChannelEntityNotificationChannelId");

                    b.HasOne("Oip.Notifications.Data.Entities.NotificationTypeEntity", "NotificationType")
                        .WithMany("Templates")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTemplateUserEntity", b =>
                {
                    b.HasOne("Oip.Notifications.Data.Entities.NotificationTemplateEntity", null)
                        .WithMany("NotificationTemplateUsers")
                        .HasForeignKey("NotificationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationUserEntity", b =>
                {
                    b.HasOne("Oip.Notifications.Data.Entities.NotificationEntity", "Notification")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.UserNotificationPreferenceEntity", b =>
                {
                    b.HasOne("Oip.Notifications.Data.Entities.NotificationChannelEntity", "NotificationChannel")
                        .WithMany("UserPreferences")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oip.Notifications.Data.Entities.NotificationTypeEntity", "NotificationType")
                        .WithMany("UserPreferences")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationChannel");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationChannelEntity", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Templates");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationEntity", b =>
                {
                    b.Navigation("NotificationUsers");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTemplateEntity", b =>
                {
                    b.Navigation("NotificationTemplateChannels");

                    b.Navigation("NotificationTemplateUsers");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationTypeEntity", b =>
                {
                    b.Navigation("Templates");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Oip.Notifications.Data.Entities.NotificationUserEntity", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
