services:
  
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    networks:
      - backend-network
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-g101k@mail.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadminhome-data:/home/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend-network
      - bridge-network
    restart: unless-stopped
    depends_on:
      - postgres
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER:-postgres}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: ${GF_ADMIN_USERNAME:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD:-P@ssw0rd}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${GF_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD:-P@ssw0rd}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/data/cert/oip.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/data/cert/oip.key
    networks:
      - backend-network
      - bridge-network
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    volumes:
      # - $HOME/.aspnet/https:/opt/keycloak/data/cert/
      - ${APPDATA}/ASP.NET/https:/opt/keycloak/data/cert/
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro
    depends_on:
      - postgres
    
    
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9001:9000"  # Native protocol
      - "9009:9009"  # Interserver communication
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - TZ=UTC
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=P@ssw0rd
    networks:
      - bridge-network

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8082:8978"
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      - clickhouse
    networks:
      - bridge-network
  
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              count: all
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    networks:
      backend-network:
  
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=P@ssw0rd
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Moscow
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      backend-network:
  
networks:
  backend-network: { }
  bridge-network:
    driver: bridge

volumes:
  n8n_data:
  postgres-data:
  pgadmin-data:
  pgadminhome-data:
  clickhouse_data:
  dbeaver-data:
  ollama: