//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oip.Api.Properties {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Oip.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ModuleModuleController_GetModuleRights_Read {
            get {
                return ResourceManager.GetString("ModuleModuleController_GetModuleRights_Read", resourceCulture);
            }
        }
        
        internal static string ModuleModuleController_GetModuleRights_Can_view_this_module {
            get {
                return ResourceManager.GetString("ModuleModuleController_GetModuleRights_Can_view_this_module", resourceCulture);
            }
        }
        
        internal static string ModuleModuleController_GetModuleRights_Edit {
            get {
                return ResourceManager.GetString("ModuleModuleController_GetModuleRights_Edit", resourceCulture);
            }
        }
        
        internal static string ModuleModuleController_GetModuleRights_Can_edit_data_in_module {
            get {
                return ResourceManager.GetString("ModuleModuleController_GetModuleRights_Can_edit_data_in_module", resourceCulture);
            }
        }
        
        internal static string ModuleModuleController_GetModuleRights_Delete {
            get {
                return ResourceManager.GetString("ModuleModuleController_GetModuleRights_Delete", resourceCulture);
            }
        }
        
        internal static string ModuleModuleController_GetModuleRights_Can_delete_data_in_module {
            get {
                return ResourceManager.GetString("ModuleModuleController_GetModuleRights_Can_delete_data_in_module", resourceCulture);
            }
        }
        
        internal static string FolderModuleController_GetModuleRights_read {
            get {
                return ResourceManager.GetString("FolderModuleController_GetModuleRights_read", resourceCulture);
            }
        }
        
        internal static string FolderModuleController_GetModuleRights_Can_view_this_module {
            get {
                return ResourceManager.GetString("FolderModuleController_GetModuleRights_Can_view_this_module", resourceCulture);
            }
        }
        
        internal static string BaseModuleController_GetModuleRights_Read {
            get {
                return ResourceManager.GetString("BaseModuleController_GetModuleRights_Read", resourceCulture);
            }
        }
        
        internal static string BaseModuleController_GetModuleRights_Can_view_this_module {
            get {
                return ResourceManager.GetString("BaseModuleController_GetModuleRights_Can_view_this_module", resourceCulture);
            }
        }
    }
}
