//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oip.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Oip.Properties.Resources_ru", typeof(Resources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WeatherForecastController_Summaries_Balmy {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Balmy", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Bracing {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Bracing", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Chilly {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Chilly", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Cool {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Cool", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Freezing {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Freezing", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Hot {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Hot", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Scorching {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Scorching", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Mild {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Mild", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Warm {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Warm", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_Summaries_Sweltering {
            get {
                return ResourceManager.GetString("WeatherForecastController_Summaries_Sweltering", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_GetModuleRights_Read {
            get {
                return ResourceManager.GetString("WeatherForecastController_GetModuleRights_Read", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_GetModuleRights_Edit {
            get {
                return ResourceManager.GetString("WeatherForecastController_GetModuleRights_Edit", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_GetModuleRights_Delete {
            get {
                return ResourceManager.GetString("WeatherForecastController_GetModuleRights_Delete", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_GetModuleRights_Can_view_this_module {
            get {
                return ResourceManager.GetString("WeatherForecastController_GetModuleRights_Can_view_this_module", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_GetModuleRights_Can_edit_data {
            get {
                return ResourceManager.GetString("WeatherForecastController_GetModuleRights_Can_edit_data", resourceCulture);
            }
        }
        
        internal static string WeatherForecastController_GetModuleRights_Can_delete_edit_data {
            get {
                return ResourceManager.GetString("WeatherForecastController_GetModuleRights_Can_delete_edit_data", resourceCulture);
            }
        }
        
        internal static string DataContextMigrationController_GetModuleRights_Can_this_module {
            get {
                return ResourceManager.GetString("DataContextMigrationController_GetModuleRights_Can_this_module", resourceCulture);
            }
        }
        
        internal static string DataContextMigrationController_GetModuleRights_Read {
            get {
                return ResourceManager.GetString("DataContextMigrationController_GetModuleRights_Read", resourceCulture);
            }
        }
    }
}
