// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oip.Discussions.Data;

#nullable disable

namespace Oip.Discussions.Data.Migrations.Postgres
{
    [DbContext(typeof(DiscussionsDbContextPostgres))]
    partial class DiscussionsDbBaseContextPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Oip.Discussions.Data.AttachmentEntity", b =>
                {
                    b.Property<long>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier of the attachment.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AttachmentId"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the comment that contains this attachment.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Original name of the attached file.");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Physical path to the attached file in storage.");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasComment("Size of the attached file in bytes.");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("MIME type or file extension of the attachment.");

                    b.Property<Guid>("StorageFileId")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the file in the storage system.");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the attachment was uploaded.");

                    b.HasKey("AttachmentId");

                    b.HasIndex("CommentId");

                    b.HasIndex("StorageFileId")
                        .IsUnique();

                    b.ToTable("Attachment", "discussions", t =>
                        {
                            t.HasComment("Represents an attachment entity associated with a comment.");
                        });
                });

            modelBuilder.Entity("Oip.Discussions.Data.CommentEditHistoryEntity", b =>
                {
                    b.Property<long>("CommentEditHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier for the comment edit history record.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CommentEditHistoryId"));

                    b.Property<long?>("CommentEntityCommentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommentEntityObjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommentEntityObjectTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the comment that was edited.");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the edit was performed.");

                    b.Property<long>("EditedByUserId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the user who performed the edit.");

                    b.Property<string>("NewContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("The content of the comment after the edit.");

                    b.Property<string>("OldContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("The content of the comment before the edit.");

                    b.HasKey("CommentEditHistoryId");

                    b.HasIndex("CommentId");

                    b.HasIndex("EditedAt");

                    b.HasIndex("EditedByUserId");

                    b.HasIndex("CommentEntityObjectTypeId", "CommentEntityObjectId", "CommentEntityCommentId");

                    b.ToTable("CommentEditHistory", "discussions", t =>
                        {
                            t.HasComment("Represents the edit history of a comment, tracking changes made to comment content.");
                        });
                });

            modelBuilder.Entity("Oip.Discussions.Data.CommentEntity", b =>
                {
                    b.Property<long>("ObjectTypeId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the object type associated with the comment.");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the object associated with the comment.");

                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier of the comment.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("Content of the comment.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the comment was created.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the comment was deleted.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the comment is deleted.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the comment was last updated.");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the user who created the comment.");

                    b.HasKey("ObjectTypeId", "ObjectId", "CommentId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.HasIndex("ObjectTypeId", "ObjectId");

                    b.ToTable("Comment", "discussions", t =>
                        {
                            t.HasComment("Represents a comment entity with content, metadata, and related associations.");
                        });
                });

            modelBuilder.Entity("Oip.Discussions.Data.MentionEntity", b =>
                {
                    b.Property<long>("MentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier of the mention.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MentionId"));

                    b.Property<long?>("CommentEntityCommentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommentEntityObjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommentEntityObjectTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the comment containing the mention.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the mention was created.");

                    b.Property<long>("MentionedUserId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the user who was mentioned.");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasComment("Position of the mention within the comment text.");

                    b.HasKey("MentionId");

                    b.HasIndex("CommentId");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("CommentId", "Position");

                    b.HasIndex("CommentEntityObjectTypeId", "CommentEntityObjectId", "CommentEntityCommentId");

                    b.ToTable("Mention", "discussions", t =>
                        {
                            t.HasComment("Represents a mention entity where a user is mentioned in a comment.");
                        });
                });

            modelBuilder.Entity("Oip.Discussions.Data.ReactionEntity", b =>
                {
                    b.Property<long>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier of the reaction.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReactionId"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the comment that was reacted to.");

                    b.Property<string>("EmojiCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Emoji code representing the reaction type (e.g., Like, Heart, etc.).");

                    b.Property<DateTimeOffset>("ReactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Timestamp when the reaction was created.");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the user who created the reaction.");

                    b.HasKey("ReactionId");

                    b.HasIndex("CommentId");

                    b.HasIndex("EmojiCode");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("Reaction", "discussions", t =>
                        {
                            t.HasComment("Represents a reaction entity where a user reacts to a comment with an emoji.");
                        });
                });

            modelBuilder.Entity("Oip.Discussions.Data.AttachmentEntity", b =>
                {
                    b.HasOne("Oip.Discussions.Data.CommentEntity", "Comment")
                        .WithMany("Attachments")
                        .HasForeignKey("CommentId")
                        .HasPrincipalKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Oip.Discussions.Data.CommentEditHistoryEntity", b =>
                {
                    b.HasOne("Oip.Discussions.Data.CommentEntity", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .HasPrincipalKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oip.Discussions.Data.CommentEntity", null)
                        .WithMany("EditHistory")
                        .HasForeignKey("CommentEntityObjectTypeId", "CommentEntityObjectId", "CommentEntityCommentId");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Oip.Discussions.Data.MentionEntity", b =>
                {
                    b.HasOne("Oip.Discussions.Data.CommentEntity", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .HasPrincipalKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oip.Discussions.Data.CommentEntity", null)
                        .WithMany("Mentions")
                        .HasForeignKey("CommentEntityObjectTypeId", "CommentEntityObjectId", "CommentEntityCommentId");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Oip.Discussions.Data.ReactionEntity", b =>
                {
                    b.HasOne("Oip.Discussions.Data.CommentEntity", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .HasPrincipalKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Oip.Discussions.Data.CommentEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("EditHistory");

                    b.Navigation("Mentions");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
