create table default.Tag
(
    TagId         UInt32,
    Name          String,
    ValueType     Enum8('Float32' = 0, 'Float64' = 1, 'Int32' = 3, 'Digital' = 4, 'String' = 5, 'Int16' = 2, 'Blog' = 6),
    Source        String,
    Descriptor    Nullable(String),
    EngUnits      Nullable(String),
    InstrumentTag Nullable(String),
    Archiving     Bool,
    Compressing   Bool,
    ExcDev        Nullable(Float64),
    ExcMin        Nullable(Float64),
    ExcMax        Nullable(Float64),
    CompDev       Nullable(Float64),
    CompMin       Nullable(Int32),
    CompMax       Nullable(Int32),
    Zero          Nullable(Int32),
    Span          Nullable(Int32),
    Location1     Nullable(Int32),
    Location2     Nullable(Int32),
    Location3     Nullable(Int32),
    Location4     Nullable(Int32),
    Location5     Nullable(Int32),
    ExDesc        Nullable(String),
    Scan          Nullable(UInt8),
    DigitalSet    Nullable(String),
    Step          Nullable(UInt8),
    UserInt1      Nullable(Int32),
    UserInt2      Nullable(Int32),
    UserInt3      Nullable(Int32),
    UserInt4      Nullable(Int32),
    UserInt5      Nullable(Int32),
    UserReal1     Nullable(Float64),
    UserReal2     Nullable(Float64),
    UserReal3     Nullable(Float64),
    UserReal4     Nullable(Float64),
    UserReal5     Nullable(Float64),
    Status        Enum8('Substituted' = -2, 'Bad' = -5, 'Shutdown' = -6, 'Timeout' = -8, 'CalcFailed' = -7, 'Good' = 0, 'OutOfRange' = -9, 'NoData' = -4, 'Questionable' = -1, 'Interpolated' = -3),
    CreationDate  DateTime64(3),
    Creator       String
)
    engine = MergeTree ORDER BY TagId
        SETTINGS index_granularity = 8192;

