// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oip.Users.Base.Contexts;

#nullable disable

namespace Oip.Users.Base.Data.Migrations.SqlServer
{
    [DbContext(typeof(UserContextSqlServer))]
    [Migration("20260627093848_DeletePhotoField_SqlServer")]
    partial class DeletePhotoField_SqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oip.Users.Base.Data.Entities.UserEntity", b =>
                {
                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation date and time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("E-mail");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("First name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the user is active");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasComment("Gets or sets the Keycloak identifier for the user.");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Last name");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Last synchronization date and time");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("User photo content type.");

                    b.Property<string>("PhotoObjectName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("User photo object name in object storage.");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("User settings in json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Last update date and time");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("User id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.ToTable("User", "usr", t =>
                        {
                            t.HasComment("User entity");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
