// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oip.Rtds.Data.Contexts;

#nullable disable

namespace Oip.Rtds.SqlServer.Migrations
{
    [DbContext(typeof(RtdsMetaContext))]
    partial class RtdsMetaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oip.Rtds.Data.Entities.TagEntity", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Compressing")
                        .HasColumnType("bit");

                    b.Property<long?>("CompressionMaxTime")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompressionMinTime")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descriptor")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("DigitalSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorCalculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interface")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Partition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("Scan")
                        .HasColumnType("bit");

                    b.Property<double>("Span")
                        .HasColumnType("float");

                    b.Property<bool>("Step")
                        .HasColumnType("bit");

                    b.Property<string>("TimeCalculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueCalculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.Property<double>("Zero")
                        .HasColumnType("float");

                    b.HasKey("TagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tag", "rtds");
                });
#pragma warning restore 612, 618
        }
    }
}
