// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oip.Rtds.Data.Contexts;

#nullable disable

namespace Oip.Rtds.SqlServer.Migrations
{
    [DbContext(typeof(RtdsMetaContextSqlServer))]
    partial class RtdsMetaContextSqlServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oip.Rtds.Data.Entities.InterfaceEntity", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Interface", "rtds");
                });

            modelBuilder.Entity("Oip.Rtds.Data.Entities.TagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier of the tag.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Compressing")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether compression is enabled for this tag.");

                    b.Property<long?>("CompressionMaxTime")
                        .HasColumnType("bigint")
                        .HasComment("Maximum time (in milliseconds) between compressed values.");

                    b.Property<long?>("CompressionMinTime")
                        .HasColumnType("bigint")
                        .HasComment("Minimum time (in milliseconds) between compressed values.\n            Values received within this period are discarded, regardless of their error margin.");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Date and time when the tag was created.");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("User or process that created the tag.");

                    b.Property<string>("Descriptor")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Description of the point (used as a comment or label).");

                    b.Property<string>("DigitalSet")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Associated digital state set name (for digital-type points).");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the point is archived.");

                    b.Property<string>("ErrorCalculation")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Formula used to calculate error values for the tag.");

                    b.Property<string>("InstrumentTag")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Reference to the source signal or channel tag.");

                    b.Property<long?>("InterfaceId")
                        .HasMaxLength(128)
                        .HasColumnType("bigint")
                        .HasComment("The interface associated with the tag.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Name of the tag.");

                    b.Property<bool>("Step")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether values are treated as step (true) or interpolated (false).");

                    b.Property<string>("TimeCalculation")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Formula used to calculate the time associated with the tag's value.\n            Default `now()`;");

                    b.Property<string>("Uom")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Engineering units (e.g., °C, PSI, m³/h).");

                    b.Property<string>("ValueCalculation")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("User-defined calculation or formula associated with the tag's value.");

                    b.Property<int>("ValueType")
                        .HasColumnType("int")
                        .HasComment("Data type of the point (e.g., Float32, Int32, Digital, String, Blob).");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tag", "rtds", t =>
                        {
                            t.HasComment("Represents the configuration and metadata of a tag.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
