[req]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[dn]
C = oi
ST = oip
CN = oip

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = oip
DNS.2 = oip-applications
DNS.3 = oip-users
DNS.4 = oip-notifications
DNS.5 = keycloak
DNS.6 = localhost
DNS.7 = host.docker.internal
IP.1 = 127.0.0.1
IP.2 = 0.0.0.0
IP.3 = ::1
